### ISSUE TITLE
Plugin does not work properly in Gnome 3.30.2.

### ISSUE THREAD

**Issue by devleifr** [danielfalk/gnome3breakreminder#1]
Plugin does not work properly in Gnome 3.30.2. Nothing happens after the passage of a predetermined period of time.

**Comment by danielfalk** [comment]
Thanks for your report.  I'm not on 3.30.2 yet, so I'll have to set up a test VM at some point.  You're welcome to tackle the problem yourself if you have any ideas,  Pull requests are welcome.

**Comment by danielfalk** [comment]
After updating to Ubuntu 20.04, I've gotten it to work on 3.36.  I'll close this for now unless there is still an issue.
