### ISSUE TITLE
multiple timer support?

### ISSUE THREAD

**Issue by jmberg** [danielfalk/gnome3breakreminder#11]
workrave supports multiple timers, that might be nice - micro breaks just to stretch for a few seconds, and regular breaks.

**Comment by danielfalk** [comment]
Thanks for your suggestion.  The point is to keep it simple and not to "lock" the screen or present an intrusive overlay.  It's more of a "nudge" than anything, but with that said, your idea is to allow for some different message based upon X number of micro-breaks that have passed?

I would like to think more of a way to give helpful functionality but it is definitely a design goal for this thing to be basic and simple.  I'm aware of tools like workrave, having used them in the past.  Those fill a niche already.  I don't want to crowd that niche and would suggest anybody desiring more advanced functionality to go ahead and use those tools instead.  Please feel free to suggest ways of making this happen, but please make it ruthlessly simple!
