### ISSUE TITLE
Adjusting the interval sets it to "NaN minutes"

### ISSUE THREAD

**Issue by imd** [danielfalk/gnome3breakreminder#3]
I'm using Ubuntu 20.04. I installed Break Reminder and tried moving the slider to change the interval from 20 minutes. As soon as I moved the slider, the displayed interval changed to "NaN minutes". It should have changed to show new intervals as I adjusted the slider.

**Comment by danielfalk** [comment]
You're right!  Thanks for the report.  I've fixed it along with some other issues I found along the way.  I'll be submitting it today.
