### ISSUE TITLE
Fails to install on GNOME 3.36

### ISSUE THREAD

**Issue by imd** [danielfalk/gnome3breakreminder#4]
I just tried installing the extension thru extensions.gnome.org. The install slider changes to an "error" alert icon.

I'm using Ubuntu 20.04.

**Comment by danielfalk** [comment]
It looks like the new version just got approved today.  Can you try again?

**Comment by imd** [comment]
Still fails with an error. I don't know if there's a way to see what revision is available on extensions.gnome.org. That would be helpful to know.

**Comment by mzur** [comment]
The extensions usually show an error when installed through the website. Reload GNOME Shell with <kbd>Alt</kbd>+<kbd>F2</kbd> and the `r` command or log out and back in, then reload/check the extensions website. This extension works fine for me with GNOME Shell 3.36.4.

**Comment by danielfalk** [comment]
Thanks mzur!  I was trying to reproduce this error myself and had to put the project down for a bit.  I had set up a VM so that I could test it cleanly.  @imd please let me know if you have tried mzur's advice or have otherwise gotten it to work.  If not, I will keep going with that VM.  And I apologize for any delay.

**Comment by imd** [comment]
I no longer have GNOME 3.36 installed, and this extension isn't listed as supporting GNOME 3.38. I tried installing it anyway and got an error, but that should be a considered a separate bug.

**Comment by danielfalk** [comment]
I just went ahead and created a VM with 3.36 to try this out, installed from extensions.gnome.org and it appears to work, so I'll go ahead and close.  Thanks for the report.
